_target_: src.models.imagenet_vit_module.ImagenetLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.ViT.VisionTransformer
  img_size: 64
  patch_size: 8
  emb_dim: 64
  n_encoder: 4
  n_head: 2
  num_classes: 200

# compile model for faster training with pytorch 2.0
compile: false
